<?php

namespace Database\Seeders\Pms;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Domains\CountryCodes\Repositories\Eloquent\Models\CountryCode;

class CountryCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countryCodes = [
            ['code' => '+93', 'name' => 'Afghanistan', 'iso_code' => 'AF'],
            ['code' => '+355', 'name' => 'Albania', 'iso_code' => 'AL'],
            ['code' => '+213', 'name' => 'Algeria', 'iso_code' => 'DZ'],
            ['code' => '+1-684', 'name' => 'American Samoa', 'iso_code' => 'AS'],
            ['code' => '+376', 'name' => 'Andorra', 'iso_code' => 'AD'],
            ['code' => '+244', 'name' => 'Angola', 'iso_code' => 'AO'],
            ['code' => '+1-264', 'name' => 'Anguilla', 'iso_code' => 'AI'],
            ['code' => '+672', 'name' => 'Antarctica', 'iso_code' => 'AQ'],
            ['code' => '+1-268', 'name' => 'Antigua and Barbuda', 'iso_code' => 'AG'],
            ['code' => '+54', 'name' => 'Argentina', 'iso_code' => 'AR'],
            ['code' => '+374', 'name' => 'Armenia', 'iso_code' => 'AM'],
            ['code' => '+297', 'name' => 'Aruba', 'iso_code' => 'AW'],
            ['code' => '+61', 'name' => 'Australia', 'iso_code' => 'AU'],
            ['code' => '+43', 'name' => 'Austria', 'iso_code' => 'AT'],
            ['code' => '+994', 'name' => 'Azerbaijan', 'iso_code' => 'AZ'],
            ['code' => '+1-242', 'name' => 'Bahamas', 'iso_code' => 'BS'],
            ['code' => '+973', 'name' => 'Bahrain', 'iso_code' => 'BH'],
            ['code' => '+880', 'name' => 'Bangladesh', 'iso_code' => 'BD'],
            ['code' => '+1-246', 'name' => 'Barbados', 'iso_code' => 'BB'],
            ['code' => '+375', 'name' => 'Belarus', 'iso_code' => 'BY'],
            ['code' => '+32', 'name' => 'Belgium', 'iso_code' => 'BE'],
            ['code' => '+501', 'name' => 'Belize', 'iso_code' => 'BZ'],
            ['code' => '+229', 'name' => 'Benin', 'iso_code' => 'BJ'],
            ['code' => '+1-441', 'name' => 'Bermuda', 'iso_code' => 'BM'],
            ['code' => '+975', 'name' => 'Bhutan', 'iso_code' => 'BT'],
            ['code' => '+591', 'name' => 'Bolivia', 'iso_code' => 'BO'],
            ['code' => '+387', 'name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA'],
            ['code' => '+267', 'name' => 'Botswana', 'iso_code' => 'BW'],
            ['code' => '+55', 'name' => 'Brazil', 'iso_code' => 'BR'],
            ['code' => '+246', 'name' => 'British Indian Ocean Territory', 'iso_code' => 'IO'],
            ['code' => '+1-284', 'name' => 'British Virgin Islands', 'iso_code' => 'VG'],
            ['code' => '+673', 'name' => 'Brunei', 'iso_code' => 'BN'],
            ['code' => '+359', 'name' => 'Bulgaria', 'iso_code' => 'BG'],
            ['code' => '+226', 'name' => 'Burkina Faso', 'iso_code' => 'BF'],
            ['code' => '+257', 'name' => 'Burundi', 'iso_code' => 'BI'],
            ['code' => '+855', 'name' => 'Cambodia', 'iso_code' => 'KH'],
            ['code' => '+237', 'name' => 'Cameroon', 'iso_code' => 'CM'],
            ['code' => '+1', 'name' => 'Canada', 'iso_code' => 'CA'],
            ['code' => '+238', 'name' => 'Cabo Verde', 'iso_code' => 'CV'],
            ['code' => '+1-345', 'name' => 'Cayman Islands', 'iso_code' => 'KY'],
            ['code' => '+236', 'name' => 'Central African Republic', 'iso_code' => 'CF'],
            ['code' => '+235', 'name' => 'Chad', 'iso_code' => 'TD'],
            ['code' => '+56', 'name' => 'Chile', 'iso_code' => 'CL'],
            ['code' => '+86', 'name' => 'China', 'iso_code' => 'CN'],
            ['code' => '+61', 'name' => 'Christmas Island', 'iso_code' => 'CX'],
            ['code' => '+61', 'name' => 'Cocos (Keeling) Islands', 'iso_code' => 'CC'],
            ['code' => '+57', 'name' => 'Colombia', 'iso_code' => 'CO'],
            ['code' => '+269', 'name' => 'Comoros', 'iso_code' => 'KM'],
            ['code' => '+243', 'name' => 'Congo (Kinshasa)', 'iso_code' => 'CD'],
            ['code' => '+242', 'name' => 'Congo (Brazzaville)', 'iso_code' => 'CG'],
            ['code' => '+682', 'name' => 'Cook Islands', 'iso_code' => 'CK'],
            ['code' => '+506', 'name' => 'Costa Rica', 'iso_code' => 'CR'],
            ['code' => '+385', 'name' => 'Croatia', 'iso_code' => 'HR'],
            ['code' => '+53', 'name' => 'Cuba', 'iso_code' => 'CU'],
            ['code' => '+599', 'name' => 'Curacao', 'iso_code' => 'CW'],
            ['code' => '+357', 'name' => 'Cyprus', 'iso_code' => 'CY'],
            ['code' => '+420', 'name' => 'Czech Republic', 'iso_code' => 'CZ'],
            ['code' => '+45', 'name' => 'Denmark', 'iso_code' => 'DK'],
            ['code' => '+253', 'name' => 'Djibouti', 'iso_code' => 'DJ'],
            ['code' => '+1-767', 'name' => 'Dominica', 'iso_code' => 'DM'],
            ['code' => '+1-809', 'name' => 'Dominican Republic', 'iso_code' => 'DO'],
            ['code' => '+670', 'name' => 'East Timor', 'iso_code' => 'TL',],
            ['code' => '+593', 'name' => 'Ecuador', 'iso_code' => 'EC'],
            ['code' => '+20', 'name' => 'Egypt', 'iso_code' => 'EG'],
            ['code' => '+503', 'name' => 'El Salvador', 'iso_code' => 'SV'],
            ['code' => '+240', 'name' => 'Equatorial Guinea', 'iso_code' => 'GQ'],
            ['code' => '+291', 'name' => 'Eritrea', 'iso_code' => 'ER'],
            ['code' => '+372', 'name' => 'Estonia', 'iso_code' => 'EE'],
            ['code' => '+268', 'name' => 'Swaziland', 'iso_code' => 'SZ'],
            ['code' => '+251', 'name' => 'Ethiopia', 'iso_code' => 'ET'],
            ['code' => '+500', 'name' => 'Falkland Islands', 'iso_code' => 'FK'],
            ['code' => '+298', 'name' => 'Faroe Islands', 'iso_code' => 'FO'],
            ['code' => '+679', 'name' => 'Fiji', 'iso_code' => 'FJ'],
            ['code' => '+358', 'name' => 'Finland', 'iso_code' => 'FI'],
            ['code' => '+33', 'name' => 'France', 'iso_code' => 'FR'],
            ['code' => '+594', 'name' => 'French Guiana', 'iso_code' => 'GF'],
            ['code' => '+689', 'name' => 'French Polynesia', 'iso_code' => 'PF'],
            ['code' => '+241', 'name' => 'Gabon', 'iso_code' => 'GA'],
            ['code' => '+220', 'name' => 'Gambia', 'iso_code' => 'GM'],
            ['code' => '+995', 'name' => 'Georgia', 'iso_code' => 'GE'],
            ['code' => '+49', 'name' => 'Germany', 'iso_code' => 'DE'],
            ['code' => '+233', 'name' => 'Ghana', 'iso_code' => 'GH'],
            ['code' => '+350', 'name' => 'Gibraltar', 'iso_code' => 'GI'],
            ['code' => '+30', 'name' => 'Greece', 'iso_code' => 'GR'],
            ['code' => '+299', 'name' => 'Greenland', 'iso_code' => 'GL'],
            ['code' => '+1-473', 'name' => 'Grenada', 'iso_code' => 'GD'],
            ['code' => '+590', 'name' => 'Guadeloupe', 'iso_code' => 'GP'],
            ['code' => '+1-671', 'name' => 'Guam', 'iso_code' => 'GU'],
            ['code' => '+502', 'name' => 'Guatemala', 'iso_code' => 'GT'],
            ['code' => '+44-1481', 'name' => 'Guernsey', 'iso_code' => 'GG'],
            ['code' => '+224', 'name' => 'Guinea', 'iso_code' => 'GN'],
            ['code' => '+245', 'name' => 'Guinea-Bissau', 'iso_code' => 'GW'],
            ['code' => '+592', 'name' => 'Guyana', 'iso_code' => 'GY'],
            ['code' => '+509', 'name' => 'Haiti', 'iso_code' => 'HT'],
            ['code' => '+504', 'name' => 'Honduras', 'iso_code' => 'HN'],
            ['code' => '+852', 'name' => 'Hong Kong', 'iso_code' => 'HK'],
            ['code' => '+36', 'name' => 'Hungary', 'iso_code' => 'HU'],
            ['code' => '+354', 'name' => 'Iceland', 'iso_code' => 'IS'],
            ['code' => '+91', 'name' => 'India', 'iso_code' => 'IN'],
            ['code' => '+62', 'name' => 'Indonesia', 'iso_code' => 'ID'],
            ['code' => '+98', 'name' => 'Iran', 'iso_code' => 'IR'],
            ['code' => '+964', 'name' => 'Iraq', 'iso_code' => 'IQ'],
            ['code' => '+353', 'name' => 'Ireland', 'iso_code' => 'IE'],
            ['code' => '+44-1624', 'name' => 'Isle of Man', 'iso_code' => 'IM'],
            ['code' => '+972', 'name' => 'Israel', 'iso_code' => 'IL'],
            ['code' => '+39', 'name' => 'Italy', 'iso_code' => 'IT'],
            ['code' => '+225', 'name' => 'Ivory Coast', 'iso_code' => 'CI'],
            ['code' => '+1-876', 'name' => 'Jamaica', 'iso_code' => 'JM'],
            ['code' => '+81', 'name' => 'Japan', 'iso_code' => 'JP'],
            ['code' => '+44-1534', 'name' => 'Jersey', 'iso_code' => 'JE'],
            ['code' => '+962', 'name' => 'Jordan', 'iso_code' => 'JO'],
            ['code' => '+7', 'name' => 'Kazakhstan', 'iso_code' => 'KZ'],
            ['code' => '+254', 'name' => 'Kenya', 'iso_code' => 'KE'],
            ['code' => '+686', 'name' => 'Kiribati', 'iso_code' => 'KI'],
            ['code' => '+383', 'name' => 'Kosovo', 'iso_code' => 'XK'],
            ['code' => '+965', 'name' => 'Kuwait', 'iso_code' => 'KW'],
            ['code' => '+996', 'name' => 'Kyrgyzstan', 'iso_code' => 'KG'],
            ['code' => '+856', 'name' => 'Laos', 'iso_code' => 'LA'],
            ['code' => '+371', 'name' => 'Latvia', 'iso_code' => 'LV'],
            ['code' => '+961', 'name' => 'Lebanon', 'iso_code' => 'LB'],
            ['code' => '+266', 'name' => 'Lesotho', 'iso_code' => 'LS'],
            ['code' => '+231', 'name' => 'Liberia', 'iso_code' => 'LR'],
            ['code' => '+218', 'name' => 'Libya', 'iso_code' => 'LY'],
            ['code' => '+423', 'name' => 'Liechtenstein', 'iso_code' => 'LI'],
            ['code' => '+370', 'name' => 'Lithuania', 'iso_code' => 'LT'],
            ['code' => '+352', 'name' => 'Luxembourg', 'iso_code' => 'LU'],
            ['code' => '+853', 'name' => 'Macau', 'iso_code' => 'MO'],
            ['code' => '+389', 'name' => 'North Macedonia', 'iso_code' => 'MK'],
            ['code' => '+261', 'name' => 'Madagascar', 'iso_code' => 'MG'],
            ['code' => '+265', 'name' => 'Malawi', 'iso_code' => 'MW'],
            ['code' => '+60', 'name' => 'Malaysia', 'iso_code' => 'MY'],
            ['code' => '+960', 'name' => 'Maldives', 'iso_code' => 'MV'],
            ['code' => '+223', 'name' => 'Mali', 'iso_code' => 'ML'],
            ['code' => '+356', 'name' => 'Malta', 'iso_code' => 'MT'],
            ['code' => '+692', 'name' => 'Marshall Islands', 'iso_code' => 'MH'],
            ['code' => '+222', 'name' => 'Mauritania', 'iso_code' => 'MR'],
            ['code' => '+230', 'name' => 'Mauritius', 'iso_code' => 'MU'],
            ['code' => '+262', 'name' => 'Mayotte', 'iso_code' => 'YT'],
            ['code' => '+52', 'name' => 'Mexico', 'iso_code' => 'MX'],
            ['code' => '+691', 'name' => 'Micronesia', 'iso_code' => 'FM'],
            ['code' => '+373', 'name' => 'Moldova', 'iso_code' => 'MD'],
            ['code' => '+377', 'name' => 'Monaco', 'iso_code' => 'MC'],
            ['code' => '+976', 'name' => 'Mongolia', 'iso_code' => 'MN'],
            ['code' => '+382', 'name' => 'Montenegro', 'iso_code' => 'ME'],
            ['code' => '+1-664', 'name' => 'Montserrat', 'iso_code' => 'MS'],
            ['code' => '+212', 'name' => 'Morocco', 'iso_code' => 'MA'],
            ['code' => '+258', 'name' => 'Mozambique', 'iso_code' => 'MZ'],
            ['code' => '+95', 'name' => 'Myanmar', 'iso_code' => 'MM'],
            ['code' => '+264', 'name' => 'Namibia', 'iso_code' => 'NA'],
            ['code' => '+674', 'name' => 'Nauru', 'iso_code' => 'NR'],
            ['code' => '+977', 'name' => 'Nepal', 'iso_code' => 'NP'],
            ['code' => '+31', 'name' => 'Netherlands', 'iso_code' => 'NL'],
            ['code' => '+687', 'name' => 'New Caledonia', 'iso_code' => 'NC'],
            ['code' => '+64', 'name' => 'New Zealand', 'iso_code' => 'NZ'],
            ['code' => '+505', 'name' => 'Nicaragua', 'iso_code' => 'NI'],
            ['code' => '+227', 'name' => 'Niger', 'iso_code' => 'NE'],
            ['code' => '+234', 'name' => 'Nigeria', 'iso_code' => 'NG'],
            ['code' => '+683', 'name' => 'Niue', 'iso_code' => 'NU'],
            ['code' => '+850', 'name' => 'North Korea', 'iso_code' => 'KP'],
            ['code' => '+1-670', 'name' => 'Northern Mariana Islands', 'iso_code' => 'MP'],
            ['code' => '+47', 'name' => 'Norway', 'iso_code' => 'NO'],
            ['code' => '+968', 'name' => 'Oman', 'iso_code' => 'OM'],
            ['code' => '+92', 'name' => 'Pakistan', 'iso_code' => 'PK'],
            ['code' => '+680', 'name' => 'Palau', 'iso_code' => 'PW'],
            ['code' => '+970', 'name' => 'Palestine', 'iso_code' => 'PS'],
            ['code' => '+507', 'name' => 'Panama', 'iso_code' => 'PA'],
            ['code' => '+675', 'name' => 'Papua New Guinea', 'iso_code' => 'PG'],
            ['code' => '+595', 'name' => 'Paraguay', 'iso_code' => 'PY'],
            ['code' => '+51', 'name' => 'Peru', 'iso_code' => 'PE'],
            ['code' => '+63', 'name' => 'Philippines', 'iso_code' => 'PH'],
            ['code' => '+48', 'name' => 'Poland', 'iso_code' => 'PL'],
            ['code' => '+351', 'name' => 'Portugal', 'iso_code' => 'PT'],
            ['code' => '+1-787', 'name' => 'Puerto Rico', 'iso_code' => 'PR'],
            ['code' => '+974', 'name' => 'Qatar', 'iso_code' => 'QA'],
            ['code' => '+262', 'name' => 'Reunion', 'iso_code' => 'RE'],
            ['code' => '+40', 'name' => 'Romania', 'iso_code' => 'RO'],
            ['code' => '+7', 'name' => 'Russia', 'iso_code' => 'RU'],
            ['code' => '+250', 'name' => 'Rwanda', 'iso_code' => 'RW'],
            ['code' => '+290', 'name' => 'Saint Helena', 'iso_code' => 'SH'],
            ['code' => '+1-869', 'name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN'],
            ['code' => '+1-758', 'name' => 'Saint Lucia', 'iso_code' => 'LC'],
            ['code' => '+590', 'name' => 'Saint Martin (French part)', 'iso_code' => 'MF'],
            ['code' => '+508', 'name' => 'Saint Pierre and Miquelon', 'iso_code' => 'PM'],
            ['code' => '+1-784', 'name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC'],
            ['code' => '+685', 'name' => 'Samoa', 'iso_code' => 'WS'],
            ['code' => '+378', 'name' => 'San Marino', 'iso_code' => 'SM'],
            ['code' => '+239', 'name' => 'Sao Tome and Principe', 'iso_code' => 'ST'],
            ['code' => '+966', 'name' => 'Saudi Arabia', 'iso_code' => 'SA'],
            ['code' => '+221', 'name' => 'Senegal', 'iso_code' => 'SN'],
            ['code' => '+381', 'name' => 'Serbia', 'iso_code' => 'RS'],
            ['code' => '+248', 'name' => 'Seychelles', 'iso_code' => 'SC'],
            ['code' => '+232', 'name' => 'Sierra Leone', 'iso_code' => 'SL'],
            ['code' => '+65', 'name' => 'Singapore', 'iso_code' => 'SG'],
            ['code' => '+421', 'name' => 'Slovakia', 'iso_code' => 'SK'],
            ['code' => '+386', 'name' => 'Slovenia', 'iso_code' => 'SI'],
            ['code' => '+677', 'name' => 'Solomon Islands', 'iso_code' => 'SB'],
            ['code' => '+252', 'name' => 'Somalia', 'iso_code' => 'SO'],
            ['code' => '+27', 'name' => 'South Africa', 'iso_code' => 'ZA'],
            ['code' => '+82', 'name' => 'South Korea', 'iso_code' => 'KR'],
            ['code' => '+211', 'name' => 'South Sudan', 'iso_code' => 'SS'],
            ['code' => '+34', 'name' => 'Spain', 'iso_code' => 'ES'],
            ['code' => '+94', 'name' => 'Sri Lanka', 'iso_code' => 'LK'],
            ['code' => '+249', 'name' => 'Sudan', 'iso_code' => 'SD'],
            ['code' => '+597', 'name' => 'Suriname', 'iso_code' => 'SR'],
            ['code' => '+268', 'name' => 'Swaziland', 'iso_code' => 'SZ'],
            ['code' => '+46', 'name' => 'Sweden', 'iso_code' => 'SE'],
            ['code' => '+41', 'name' => 'Switzerland', 'iso_code' => 'CH'],
            ['code' => '+963', 'name' => 'Syria', 'iso_code' => 'SY'],
            ['code' => '+886', 'name' => 'Taiwan', 'iso_code' => 'TW'],
            ['code' => '+992', 'name' => 'Tajikistan', 'iso_code' => 'TJ'],
            ['code' => '+255', 'name' => 'Tanzania', 'iso_code' => 'TZ'],
            ['code' => '+66', 'name' => 'Thailand', 'iso_code' => 'TH'],
            ['code' => '+228', 'name' => 'Togo', 'iso_code' => 'TG'],
            ['code' => '+690', 'name' => 'Tokelau', 'iso_code' => 'TK'],
            ['code' => '+676', 'name' => 'Tonga', 'iso_code' => 'TO'],
            ['code' => '+1-868', 'name' => 'Trinidad and Tobago', 'iso_code' => 'TT'],
            ['code' => '+216', 'name' => 'Tunisia', 'iso_code' => 'TN'],
            ['code' => '+90', 'name' => 'Turkey', 'iso_code' => 'TR'],
            ['code' => '+993', 'name' => 'Turkmenistan', 'iso_code' => 'TM'],
            ['code' => '+1-649', 'name' => 'Turks and Caicos Islands', 'iso_code' => 'TC'],
            ['code' => '+688', 'name' => 'Tuvalu', 'iso_code' => 'TV'],
            ['code' => '+256', 'name' => 'Uganda', 'iso_code' => 'UG'],
            ['code' => '+380', 'name' => 'Ukraine', 'iso_code' => 'UA'],
            ['code' => '+971', 'name' => 'United Arab Emirates', 'iso_code' => 'AE'],
            ['code' => '+44', 'name' => 'United Kingdom', 'iso_code' => 'GB'],
            ['code' => '+1', 'name' => 'United States', 'iso_code' => 'US'],
            ['code' => '+598', 'name' => 'Uruguay', 'iso_code' => 'UY'],
            ['code' => '+998', 'name' => 'Uzbekistan', 'iso_code' => 'UZ'],
            ['code' => '+678', 'name' => 'Vanuatu', 'iso_code' => 'VU'],
            ['code' => '+379', 'name' => 'Vatican City', 'iso_code' => 'VA'],
            ['code' => '+58', 'name' => 'Venezuela', 'iso_code' => 'VE'],
            ['code' => '+84', 'name' => 'Vietnam', 'iso_code' => 'VN'],
            ['code' => '+681', 'name' => 'Wallis and Futuna', 'iso_code' => 'WF'],
            ['code' => '+212', 'name' => 'Western Sahara', 'iso_code' => 'EH'],
            ['code' => '+967', 'name' => 'Yemen', 'iso_code' => 'YE'],
            ['code' => '+260', 'name' => 'Zambia', 'iso_code' => 'ZM'],
            ['code' => '+263', 'name' => 'Zimbabwe', 'iso_code' => 'ZW'],
        ];

        $now = Carbon::now();

        foreach ($countryCodes as $country) {
            CountryCode::updateOrInsert(
                [
                    'name' => $country['name'],
                    'iso_code' => $country['iso_code'],
                ],
                [
                    'code' => $country['code'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }

    }
}
